@HotelWebAPI_HostAddress = http://localhost:5035

GET {{HotelWebAPI_HostAddress}}/bookings/
Accept: application/json

###

GET {{HotelWebAPI_HostAddress}}/room/0
Accept: application/json

###

DELETE {{HotelWebAPI_HostAddress}}/clients/6
Accept: application/json

###

PUT {{HotelWebAPI_HostAddress}}/rooms/12
Content-Type: application/json
Accept: application/json

{   
    "IsAvailable": false, 
    "NightPrice": 500, 
    "RoomType": "Double"
}

###

GET {{HotelWebAPI_HostAddress}}/booking/
Accept: application/json

###