@HotelWebAPI_HostAddress = http://localhost:5035

GET {{HotelWebAPI_HostAddress}}/bookings/
Accept: application/json

###

GET {{HotelWebAPI_HostAddress}}/room/1
Accept: application/json

###

DELETE {{HotelWebAPI_HostAddress}}/bookings/7
Accept: application/json

###

PUT {{HotelWebAPI_HostAddress}}/rooms/8
Content-Type: application/json
Accept: application/json

{   
    "IsAvaiable": false, 
    "NightPrice": 500, 
    "RoomType": "Double"
}

###

GET {{HotelWebAPI_HostAddress}}/booking/
Accept: application/json

###

POST {{HotelWebAPI_HostAddress}}/booking_room/
Content-Type: application/json
Accept: application/json

{
    "RoomNumber": 98, 
    "RoomType": 0,
    "NightPrice": 200, 
    "IsAvaiable": true, 
    "CheckInDate": "2021-06-01",
    "CheckoutDate": "2021-06-10"
}

###